# SPDX-License-Identifier: ice License 1.0

development: true
logger:
  encoder: console
  level: debug
self:
  wintr/sms:
    messageServiceSIDs:
      us: bogus # not running tests for sms anyway due to expired creds
